# Generated by Django 4.2.1 on 2023-07-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_toko', '0003_remove_pesanan_jumlah_remove_pesanan_pilihan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesanan',
            name='produk',
        ),
        migrations.RemoveField(
            model_name='pesanan',
            name='status',
        ),
    ]
