# Generated by Django 4.2.1 on 2023-07-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_toko', '0004_remove_pesanan_produk_remove_pesanan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkahm',
            name='harga_per_dus',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
