# Generated by Django 4.2.1 on 2023-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_toko', '0005_alter_produkahm_harga_per_dus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='total_harga',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
