# Generated by Django 4.2.1 on 2023-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_toko', '0006_alter_pembelian_total_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembelian',
            name='harga_pembelian',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesananitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
