# Generated by Django 4.2.1 on 2023-07-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_toko', '0008_pesanan_alamat_pengiriman_pesanan_catatan_pembeli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='konfirmasi_pesanan',
            field=models.CharField(choices=[('DITERIMA', 'DITERIMA'), ('BELUM DITERIMA', 'BELUM DITERIMA')], default='BELUM DITERIMA    ', max_length=30),
        ),
    ]
