# Generated by Django 4.2.1 on 2023-07-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_toko', '0009_pesanan_konfirmasi_pesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='konfirmasi_pesanan',
            field=models.CharField(choices=[('DITERIMA', 'DITERIMA'), ('BELUM DITERIMA', 'BELUM DITERIMA')], default='BELUM DITERIMA ', max_length=30),
        ),
    ]
