# Generated by Django 4.2.1 on 2023-07-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_toko', '0010_alter_pesanan_konfirmasi_pesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pemabayaran/%Y/%m/%d/'),
        ),
    ]
