# Generated by Django 4.2.1 on 2023-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_toko', '0012_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkahm',
            name='deskripsi_produk',
            field=models.TextField(null=True),
        ),
    ]
