# Generated by Django 4.2.1 on 2023-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_keranjangitem_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keranjang',
            name='totals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
